repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.1
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
        args: ["--check", "--diff"]
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.5
    hooks:
      - id: uv-lock
