reporters = [
    [
        "diff",
        "--unified",
        "--color",
        "--suppress-common-lines",
        "--label",
        "received",
        "--label",
        "approved",
        "%received",
        "%approved",
    ],
]
